### ISSUE TITLE
[B42] Cannot Start A Fire

### ISSUE THREAD

**Issue by dcarrol3** [hypnotoadtrance/MoreTraits#187] opened 2024-12-21 15:13 UTC
I'm unable to start a fire using this mod in B42. I narrowed the issue down to this specific mod. When the mod is not used, I cannot reproduce. I tried the BBQ, Antique Stove & Fireplace. I get an error message in the bottom right corner whenever I attempt to.

If there is a way to pull the error logs for you, please let me know.

![20241221093437_1](https://github.com/user-attachments/assets/16b89121-532e-4df7-940a-8d16ea7b10bb)

**Comment by hypnotoadtrance** [comment] 2024-12-21 15:16
If you have the  Burn Ward Patient trait, the inability to start fires is intended behaviour (though the error is not). If you are not running Burn Ward Patient and still receiving this error regardless, then this is definitely a bug related to the way Burn Ward checks for fire sources.

**Comment by dcarrol3** [comment] 2024-12-21 15:19
I am not using the Burn Ward Patient trait.

**Comment by dcarrol3** [comment] 2024-12-21 15:21
Thanks for the great mod and looking into this issue!

**Comment by hypnotoadtrance** [comment] 2024-12-22 01:58
Issue resolved in [f612d5b](https://github.com/hypnotoadtrance/MoreTraits/commit/f612d5b109f138ab4416d0ace8605463c7e02526), pending release. Thank you for your report.

**Closed by hypnotoadtrance** 2024-12-22 01:58 UTC
